#!/bin/bash

wclean all > /dev/null

wmake libso Incompressible/

if (( $? )) ; then 
    echo "olaFlow multiphase incompressible turbulence library compilation failed"
    exit; else
    echo -e "\n\nolaFlow multiphase incompressible turbulence library compiled successfully for $WM_PROJECT $WM_PROJECT_VERSION\n\n\n";   
fi

wmake libso Compressible/

if (( $? )) ; then 
    echo "olaFlow multiphase compressible turbulence library compilation failed"
    exit; else
    echo -e "\n\nolaFlow multiphase compressible turbulence library compiled successfully for $WM_PROJECT $WM_PROJECT_VERSION\n\n\n";   
fi

wclean all > /dev/null

