#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

read -p "Clearing case. Are you sure? (y/N)" -n 1 -r
if ! [[ $REPLY =~ ^[Yy]$ ]]
then
    exit
fi

cleanCase

rm -rf 0

#------------------------------------------------------------------------------
